export const STRINGS = {
  welcome: 'Welcome',
  start: 'Start',
  capture: 'Capture',
  captureId: 'Capture ID',
  captureSelfie: 'Capture Selfie',
  upload: 'Upload',
  done: 'Done',
  next: 'Next',
  preview: 'Preview',
  selectFile: 'Select File',
  uploadSelectedFile: 'Upload Selected File',
  ok: 'OK',
  cancel: 'Cancel',
  fileUploadingSuccess: 'File Uploading Success',
  uploadingSuccessMsg: 'Your file has been uploaded successfully',
  fileUploadingFailed: 'File Uploading Failed',
  error: 'Something went wrong. Please try again later.',
  cameraPermissionTitle: '"Tmam" Would Like to Access Your Camera Roll',
  cameraPermissionDescription:
    'This allows BeFamily to share photos from your library and save photos to your camera roll.',
  enableLibraryAccess: 'Enable Library Access',
};
